# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FirebaseMessaging'
  # Pods for Simple

  target 'SimpleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
